"""Core module for AutoPerfPy."""

from trackiq_core.utils import (
    AnalysisResult,
    BaseAnalyzer,
    BaseBenchmark,
    BaseMonitor,
    BatchEfficiencyAnalyzer,
    DataLoader,
    EfficiencyCalculator,
    EfficiencyMetrics,
    LatencyStats,
    MetricComparison,
    PerformanceComparator,
    RegressionDetector,
    RegressionThreshold,
)

from .dnn_pipeline import (
    DNNPipelineCalculator,
    DNNPipelineParser,
    EngineOptimizationMetrics,
    InferenceRun,
    LayerTiming,
    MemoryTransfer,
)
from .tegrastats import (
    CPUCoreStats,
    GPUStats,
    MemoryStats,
    TegrastatsAggregateStats,
    TegrastatsCalculator,
    TegrastatsParser,
    TegrastatsSnapshot,
    ThermalStats,
)

__all__ = [
    "BaseAnalyzer",
    "BaseBenchmark",
    "BaseMonitor",
    "AnalysisResult",
    "DataLoader",
    "LatencyStats",
    "PerformanceComparator",
    "RegressionDetector",
    "RegressionThreshold",
    "MetricComparison",
    "EfficiencyMetrics",
    "EfficiencyCalculator",
    "BatchEfficiencyAnalyzer",
    "TegrastatsParser",
    "TegrastatsCalculator",
    "TegrastatsSnapshot",
    "TegrastatsAggregateStats",
    "CPUCoreStats",
    "GPUStats",
    "MemoryStats",
    "ThermalStats",
    "DNNPipelineParser",
    "DNNPipelineCalculator",
    "InferenceRun",
    "LayerTiming",
    "MemoryTransfer",
    "EngineOptimizationMetrics",
]
