"""Core module for AutoPerfPy."""

from trackiq.core import (
    BaseAnalyzer,
    BaseBenchmark,
    BaseMonitor,
    AnalysisResult,
    DataLoader,
    LatencyStats,
    PerformanceComparator,
    RegressionDetector,
    RegressionThreshold,
    MetricComparison,
    EfficiencyMetrics,
    EfficiencyCalculator,
    BatchEfficiencyAnalyzer,
)
from .tegrastats import (
    TegrastatsParser,
    TegrastatsCalculator,
    TegrastatsSnapshot,
    TegrastatsAggregateStats,
    CPUCoreStats,
    GPUStats,
    MemoryStats,
    ThermalStats,
)
from .dnn_pipeline import (
    DNNPipelineParser,
    DNNPipelineCalculator,
    InferenceRun,
    LayerTiming,
    MemoryTransfer,
    EngineOptimizationMetrics,
)

__all__ = [
    "BaseAnalyzer",
    "BaseBenchmark",
    "BaseMonitor",
    "AnalysisResult",
    "DataLoader",
    "LatencyStats",
    "PerformanceComparator",
    "RegressionDetector",
    "RegressionThreshold",
    "MetricComparison",
    "EfficiencyMetrics",
    "EfficiencyCalculator",
    "BatchEfficiencyAnalyzer",
    "TegrastatsParser",
    "TegrastatsCalculator",
    "TegrastatsSnapshot",
    "TegrastatsAggregateStats",
    "CPUCoreStats",
    "GPUStats",
    "MemoryStats",
    "ThermalStats",
    "DNNPipelineParser",
    "DNNPipelineCalculator",
    "InferenceRun",
    "LayerTiming",
    "MemoryTransfer",
    "EngineOptimizationMetrics",
]
