"""PDF report generation for performance analysis.

The PDF report is generated by first creating an HTML report (using HTMLReportGenerator)
and then converting it to PDF. This ensures visual consistency between HTML and PDF outputs.

Conversion backends (in order of preference):
1. Playwright (headless browser) - Best quality, renders JavaScript/Plotly charts
2. pdfkit (wkhtmltopdf) - Good quality, renders JavaScript with delay
3. weasyprint - Pure Python, but does NOT render JavaScript charts
4. Fallback - Basic matplotlib-based PDF with just text/metadata
"""

import os
import tempfile
from datetime import datetime
from typing import Any, Dict, List

# Try to import playwright for best HTML-to-PDF conversion (renders JavaScript)
PLAYWRIGHT_AVAILABLE = False
try:
    from playwright.sync_api import sync_playwright

    PLAYWRIGHT_AVAILABLE = True
except ImportError:
    pass

# Fallback: try pdfkit (requires wkhtmltopdf, renders JS with delay)
PDFKIT_AVAILABLE = False
try:
    import pdfkit

    PDFKIT_AVAILABLE = True
except ImportError:
    pass

# Fallback: weasyprint (pure Python, but NO JavaScript support)
WEASYPRINT_AVAILABLE = False
try:
    from weasyprint import HTML as WeasyHTML

    WEASYPRINT_AVAILABLE = True
except ImportError:
    pass


class PDFReportGenerator:
    """Generate PDF reports from performance analysis.

    The PDF is generated by creating an HTML report first and converting it to PDF.
    This ensures the PDF has the same layout and charts as the HTML report.

    Supports two backends:
    - weasyprint (pure Python, recommended)
    - pdfkit (requires wkhtmltopdf system dependency)

    If neither is available, falls back to a basic text-based PDF.
    """

    def __init__(
        self,
        title: str = "Performance Analysis Report",
        author: str = "AutoPerfPy",
        theme: str = "light",
    ):
        """Initialize PDF report generator.

        Args:
            title: Report title
            author: Report author name
            theme: Color theme ('light' or 'dark')
        """
        self.title = title
        self.author = author
        self.theme = theme
        self.metadata: Dict[str, Any] = {}
        self._html_generator = None

    def _get_html_generator(self):
        """Lazy-load HTMLReportGenerator to avoid circular imports."""
        if self._html_generator is None:
            from .html_generator import HTMLReportGenerator

            self._html_generator = HTMLReportGenerator(
                title=self.title,
                author=self.author,
                theme=self.theme,
            )
            # Copy metadata
            for key, value in self.metadata.items():
                self._html_generator.add_metadata(key, value)
        return self._html_generator

    def add_metadata(self, key: str, value: Any) -> None:
        """Add metadata to report.

        Args:
            key: Metadata key
            value: Metadata value
        """
        self.metadata[key] = value
        if self._html_generator:
            self._html_generator.add_metadata(key, value)

    def add_summary_item(
        self,
        label: str,
        value: Any,
        unit: str = "",
        status: str = "neutral",
    ) -> None:
        """Add an item to the executive summary.

        Args:
            label: Item label
            value: Item value
            unit: Unit of measurement
            status: Status indicator ('good', 'warning', 'critical', 'neutral')
        """
        self._get_html_generator().add_summary_item(label, value, unit, status)

    def add_section(self, name: str, description: str = "") -> None:
        """Add a section to the report.

        Args:
            name: Section name
            description: Section description
        """
        self._get_html_generator().add_section(name, description)

    def add_html_figure(
        self,
        html_content: str,
        caption: str = "",
        section: str = "General",
        description: str = "",
    ) -> None:
        """Add an HTML figure fragment (e.g. Plotly chart) to the report.

        Args:
            html_content: Raw HTML fragment (div + script from e.g. fig.to_html())
            caption: Caption for the figure
            section: Section name to group the figure under
            description: Additional description text
        """
        self._get_html_generator().add_html_figure(
            html_content, caption, section, description
        )

    def add_table(
        self,
        title: str,
        headers: List[str],
        rows: List[List[Any]],
        section: str = "General",
    ) -> None:
        """Add a data table to the report.

        Args:
            title: Table title
            headers: Column headers
            rows: Table data rows
            section: Section to place the table in
        """
        self._get_html_generator().add_table(title, headers, rows, section)

    def add_charts_from_data(
        self,
        samples: List[Dict],
        summary: Dict[str, Any],
    ) -> None:
        """Add all charts from sample data (same as HTML report).

        Args:
            samples: List of sample dictionaries from collector export
            summary: Summary statistics dictionary
        """
        try:
            from .charts import (
                samples_to_dataframe,
                ensure_throughput_column,
                add_charts_to_html_report,
            )

            df = samples_to_dataframe(samples)
            ensure_throughput_column(df)
            add_charts_to_html_report(self._get_html_generator(), df, summary)
        except ImportError:
            pass  # charts module or dependencies not available

    def _convert_html_to_pdf_playwright(self, html_path: str, pdf_path: str) -> bool:
        """Convert HTML to PDF using Playwright (headless browser).

        This is the best option as it fully renders JavaScript (Plotly charts).
        """
        if not PLAYWRIGHT_AVAILABLE:
            return False
        try:
            with sync_playwright() as p:
                browser = p.chromium.launch()
                page = browser.new_page()
                # Load the HTML file
                page.goto(f"file://{os.path.abspath(html_path)}")
                # Wait for Plotly charts to render
                page.wait_for_timeout(2000)
                # Generate PDF with print media
                page.pdf(
                    path=pdf_path,
                    format="A4",
                    margin={
                        "top": "10mm",
                        "right": "10mm",
                        "bottom": "10mm",
                        "left": "10mm",
                    },
                    print_background=True,
                )
                browser.close()
            return True
        except Exception:
            return False

    def _convert_html_to_pdf_pdfkit(self, html_path: str, pdf_path: str) -> bool:
        """Convert HTML to PDF using pdfkit (wkhtmltopdf).

        Renders JavaScript with a delay, good fallback option.
        """
        if not PDFKIT_AVAILABLE:
            return False
        try:
            options = {
                "page-size": "A4",
                "margin-top": "10mm",
                "margin-right": "10mm",
                "margin-bottom": "10mm",
                "margin-left": "10mm",
                "encoding": "UTF-8",
                "enable-local-file-access": None,
                "javascript-delay": 2000,  # Wait for Plotly charts to render
            }
            pdfkit.from_file(html_path, pdf_path, options=options)
            return True
        except Exception:
            return False

    def _convert_html_to_pdf_weasyprint(self, html_path: str, pdf_path: str) -> bool:
        """Convert HTML to PDF using weasyprint.

        Note: weasyprint does NOT execute JavaScript, so Plotly charts won't render.
        Only use as last resort or when charts are not needed.
        """
        if not WEASYPRINT_AVAILABLE:
            return False
        try:
            WeasyHTML(filename=html_path).write_pdf(pdf_path)
            return True
        except Exception:
            return False

    def _create_fallback_pdf(self, pdf_path: str) -> bool:
        """Create a basic fallback PDF when no HTML-to-PDF converter is available."""
        try:
            import matplotlib.pyplot as plt
            from matplotlib.backends.backend_pdf import PdfPages

            with PdfPages(pdf_path) as pdf:
                # Title page
                fig = plt.figure(figsize=(8.5, 11))
                ax = fig.add_subplot(111)
                ax.axis("off")
                ax.text(
                    0.5,
                    0.85,
                    self.title,
                    ha="center",
                    va="top",
                    fontsize=24,
                    fontweight="bold",
                    transform=ax.transAxes,
                )
                ax.text(
                    0.5,
                    0.78,
                    "Performance Analysis Report",
                    ha="center",
                    va="top",
                    fontsize=14,
                    color="gray",
                    transform=ax.transAxes,
                )

                y_pos = 0.65
                for key, value in self.metadata.items():
                    ax.text(
                        0.25,
                        y_pos,
                        f"{key}:",
                        ha="right",
                        va="top",
                        fontsize=11,
                        fontweight="bold",
                        transform=ax.transAxes,
                    )
                    ax.text(
                        0.27,
                        y_pos,
                        str(value),
                        ha="left",
                        va="top",
                        fontsize=11,
                        transform=ax.transAxes,
                    )
                    y_pos -= 0.05

                timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                ax.text(
                    0.5,
                    0.15,
                    f"Generated on {timestamp}",
                    ha="center",
                    va="bottom",
                    fontsize=9,
                    style="italic",
                    color="gray",
                    transform=ax.transAxes,
                )
                ax.text(
                    0.5,
                    0.10,
                    "Note: Install weasyprint or pdfkit for full PDF reports with charts.",
                    ha="center",
                    va="bottom",
                    fontsize=9,
                    color="red",
                    transform=ax.transAxes,
                )

                pdf.savefig(fig, bbox_inches="tight")
                plt.close(fig)

                # PDF metadata
                d = pdf.infodict()
                d["Title"] = self.title
                d["Author"] = self.author
                d["Subject"] = "Performance Analysis Report"
                d["CreationDate"] = datetime.now()

            return True
        except Exception:
            return False

    def generate_pdf(
        self,
        output_path: str,
        include_summary: bool = True,
    ) -> str:
        """Generate PDF report.

        Creates an HTML report first, then converts it to PDF.

        Args:
            output_path: Path to save PDF file
            include_summary: Whether to include a summary section

        Returns:
            Path to generated PDF
        """
        os.makedirs(
            os.path.dirname(output_path) if os.path.dirname(output_path) else ".",
            exist_ok=True,
        )

        # Generate HTML first
        html_gen = self._get_html_generator()
        with tempfile.NamedTemporaryFile(
            suffix=".html", delete=False, mode="w", encoding="utf-8"
        ) as tmp:
            html_path = tmp.name

        try:
            html_gen.generate_html(html_path, include_summary=include_summary)

            # Try converters in order of quality:
            # 1. Playwright (best - full JavaScript/Plotly support)
            # 2. pdfkit/wkhtmltopdf (good - JavaScript with delay)
            # 3. weasyprint (basic - no JavaScript, charts won't render)
            # 4. matplotlib fallback (text only)

            if self._convert_html_to_pdf_playwright(html_path, output_path):
                return output_path
            if self._convert_html_to_pdf_pdfkit(html_path, output_path):
                return output_path
            if self._convert_html_to_pdf_weasyprint(html_path, output_path):
                return output_path

            # Fallback: basic matplotlib PDF
            if self._create_fallback_pdf(output_path):
                return output_path

            raise RuntimeError(
                "No PDF conversion backend available. "
                "For best results with charts, install playwright: "
                "pip install playwright && playwright install chromium\n"
                "Or install pdfkit: pip install pdfkit (requires wkhtmltopdf)\n"
                "Or install weasyprint: pip install weasyprint (no chart support)"
            )
        finally:
            # Clean up temp HTML
            try:
                os.unlink(html_path)
            except OSError:
                pass

    def generate_html(
        self,
        output_path: str,
        include_summary: bool = True,
    ) -> str:
        """Generate HTML report (convenience method).

        Args:
            output_path: Path to save HTML file
            include_summary: Whether to include a summary section

        Returns:
            Path to generated HTML
        """
        return self._get_html_generator().generate_html(
            output_path, include_summary=include_summary
        )

    def clear(self) -> None:
        """Clear all data and reset the generator."""
        self.metadata = {}
        if self._html_generator:
            self._html_generator.clear()
            self._html_generator = None


__all__ = ["PDFReportGenerator"]
